import curses
import random
import time

# İngilizce-Türkçe kelime sözlüğü seviyelere göre ayrılmıştır
word_dict = {
    "A1": {
    "apple": "elma",
    "banana": "muz",
    "orange": "portakal",
    "grape": "üzüm",
    "watermelon": "karpuz",
    "dog": "köpek",
    "cat": "kedi",
    "bird": "kuş",
    "fish": "balık",
    "cow": "inek",
    "house": "ev",
    "car": "araba",
    "book": "kitap",
    "pen": "kalem",
    "tree": "ağaç",
    "sun": "güneş",
    "moon": "ay",
    "star": "yıldız",
    "cloud": "bulut",
    "rain": "yağmur",
    "snow": "kar",
    "happy": "mutlu",
    "sad": "üzgün",
    "angry": "kızgın",
    "hungry": "aç",
    "thirsty": "susamış",
    "tired": "yorgun",
    "hot": "sıcak",
    "cold": "soğuk",
    "big": "büyük",
    "small": "küçük",
    "fast": "hızlı",
    "slow": "yavaş",
    "new": "yeni",
    "old": "eski",
    "clean": "temiz",
    "dirty": "kirli",
    "open": "açık",
    "closed": "kapalı",
    "blue": "mavi",
    "red": "kırmızı",
    "green": "yeşil",
    "yellow": "sarı",
    "black": "siyah",
    "white": "beyaz",
    "pink": "pembe",
    "purple": "mor",
    "brown": "kahverengi",
    "orange": "turuncu",
    "family": "aile",
    "mother": "anne",
    "father": "baba",
    "sister": "kız kardeş",
    "brother": "erkek kardeş",
    "baby": "bebek",
    "friend": "arkadaş",
    "teacher": "öğretmen",
    "student": "öğrenci",
    "doctor": "doktor",
    "nurse": "hemşire",
    "police": "polis",
    "firefighter": "itfaiyeci",
    "cook": "aşçı",
    "driver": "şoför",
    "farmer": "çiftçi",
    "waiter": "garson",
    "singer": "şarkıcı",
    "actor": "aktör",
    "artist": "sanatçı",
    "table": "masa",
    "chair": "sandalye",
    "window": "pencere",
    "door": "kapı",
    "kitchen": "mutfak",
    "bedroom": "yatak odası",
    "bathroom": "banyo",
    "garden": "bahçe",
    "cup": "fincan",
    "plate": "tabak",
    "knife": "bıçak",
    "fork": "çatal",
    "spoon": "kaşık",
    "bread": "ekmek",
    "milk": "süt",
    "water": "su",
    "coffee": "kahve",
    "tea": "çay",
    "sugar": "şeker",
    "salt": "tuz",
    "chicken": "tavuk",
    "meat": "et",
    "egg": "yumurta",
    "rice": "pirinç",
    "pasta": "makarna",
    "apple juice": "elma suyu",
    "orange juice": "portakal suyu",
    "fish": "balık",
    "banana": "muz",
    "pear": "armut",
    "peach": "şeftali",
    "grape": "üzüm",
    "melon": "kavun",
    "watermelon": "karpuz",
    "pineapple": "ananas",
    "strawberry": "çilek",
    "cherry": "kiraz",
    "dog": "köpek",
    "cat": "kedi",
    "rabbit": "tavşan",
    "bird": "kuş",
    "duck": "ördek",
    "cow": "inek",
    "horse": "at",
    "sheep": "koyun",
    "goat": "keçi",
    "car": "araba",
    "bus": "otobüs",
    "bicycle": "bisiklet",
    "train": "tren",
    "plane": "uçak",
    "boat": "tekne",
    "ship": "gemi",
    "motorcycle": "motosiklet",
    "ball": "top",
    "book": "kitap",
    "pen": "kalem",
    "pencil": "kurşun kalem",
    "eraser": "silgi",
    "notebook": "defter",
    "school": "okul",
    "teacher": "öğretmen",
    "student": "öğrenci",
    "board": "tahta",
    "chalk": "tebeşir",
    "computer": "bilgisayar",
    "phone": "telefon",
    "television": "televizyon",
    "radio": "radyo",
    "camera": "kamera",
    "lamp": "lamba",
    "bed": "yatak",
    "clock": "saat",
    "bag": "çanta",
    "key": "anahtar",
    "money": "para",
    "wallet": "cüzdan",
    "hat": "şapka",
    "shoes": "ayakkabı",
    "clothes": "kıyafet",
    "shirt": "gömlek",
    "pants": "pantolon",
    "dress": "elbise",
    "skirt": "etek",
    "socks": "çorap",
    "jacket": "ceket",
    "coat": "mont",
    "gloves": "eldiven",
    "scarf": "atkı"
    },
    "A2": {
    "airport": "havaalanı",
    "ambulance": "ambulans",
    "apartment": "apartman",
    "appointment": "randevu",
    "backpack": "sırt çantası",
    "balloon": "balon",
    "beach": "plaj",
    "blanket": "battaniye",
    "bridge": "köprü",
    "building": "bina",
    "butter": "tereyağı",
    "candle": "mum",
    "carpet": "halı",
    "castle": "şato",
    "ceiling": "tavan",
    "cheese": "peynir",
    "city": "şehir",
    "cliff": "uçurum",
    "clinic": "klinik",
    "closet": "dolap",
    "countryside": "kırsal alan",
    "cushion": "minder",
    "desert": "çöl",
    "dishwasher": "bulaşık makinesi",
    "dolphin": "yunus",
    "downtown": "şehir merkezi",
    "fireplace": "şömine",
    "forest": "orman",
    "garage": "garaj",
    "garden": "bahçe",
    "gym": "spor salonu",
    "helicopter": "helikopter",
    "highway": "otoyol",
    "hospital": "hastane",
    "island": "ada",
    "jungle": "orman",
    "kettle": "su ısıtıcısı",
    "kitchen": "mutfak",
    "lake": "göl",
    "lawn": "çim",
    "library": "kütüphane",
    "lighthouse": "deniz feneri",
    "market": "pazar",
    "microwave": "mikrodalga",
    "mirror": "ayna",
    "mountain": "dağ",
    "museum": "müze",
    "neighborhood": "mahalle",
    "ocean": "okyanus",
    "oven": "fırın",
    "palace": "saray",
    "park": "park",
    "parking lot": "otopark",
    "path": "patika",
    "pillow": "yastık",
    "playground": "oyun alanı",
    "port": "liman",
    "restaurant": "restoran",
    "river": "nehir",
    "roof": "çatı",
    "shelf": "raf",
    "sidewalk": "kaldırım",
    "stadium": "stadyum",
    "subway": "metro",
    "supermarket": "süpermarket",
    "swimming pool": "yüzme havuzu",
    "theater": "tiyatro",
    "tower": "kule",
    "traffic": "trafik",
    "train station": "tren istasyonu",
    "tunnel": "tünel",
    "village": "köy",
    "volcano": "yanardağ",
    "warehouse": "depo",
    "waterfall": "şelale",
    "windmill": "yeldeğirmeni",
    "backyard": "arka bahçe",
    "balcony": "balkon",
    "basement": "bodrum",
    "battery": "pil",
    "bedside table": "komodin",
    "bench": "bank",
    "blender": "blender",
    "bookstore": "kitapçı",
    "boulevard": "bulvar",
    "campground": "kamp alanı",
    "canteen": "kantin",
    "ceiling fan": "tavan vantilatörü",
    "chandelier": "avize",
    "circus": "sirk",
    "coast": "kıyı",
    "coffee table": "sehpa",
    "conference room": "toplantı odası",
    "crosswalk": "yaya geçidi",
    "curtain": "perde",
    "deck": "güverte",
    "department store": "büyük mağaza",
    "detergent": "deterjan",
    "diving board": "dalgıç tahtası",
    "fence": "çit",
    "fire extinguisher": "yangın söndürücü",
    "fishing rod": "olta",
    "fountain": "çeşme",
    "garage door": "garaj kapısı",
    "giraffe": "zürafa",
    "goldfish": "japon balığı",
    "greenhouse": "sera",
    "grocery store": "market",
    "hair dryer": "saç kurutma makinesi",
    "hammock": "hamak",
    "hatstand": "şapka askısı",
    "hedge": "çit bitkisi",
    "horse stable": "ahır",
    "hot air balloon": "sıcak hava balonu",
    "ice cream truck": "dondurma kamyonu",
    "laundry room": "çamaşır odası",
    "lemonade stand": "limonata standı",
    "lifeguard": "cankurtaran",
    "locker": "kilitli dolap",
    "mailbox": "posta kutusu",
    "manhole": "menhol",
    "marketplace": "çarşı",
    "mountain range": "sıradağlar",
    "nest": "yuva",
    "nightstand": "komodin",
    "nursery": "kreş",
    "observatory": "rasathane",
    "office building": "ofis binası",
    "outlet": "priz",
    "painting": "resim",
    "parking meter": "parkmetre",
    "pathway": "yol",
    "pharmacy": "eczane",
    "picnic area": "piknik alanı",
    "plantation": "plantasyon",
    "playpen": "oyun parkı",
    "post office": "postane",
    "pothole": "çukur",
    "power outlet": "elektrik prizi",
    "public restroom": "umumi tuvalet",
    "recycling bin": "geri dönüşüm kutusu",
    "rocking chair": "sallanan sandalye",
    "roller coaster": "lunapark treni",
    "safety cone": "güvenlik konisi",
    "sandbox": "kum havuzu",
    "seesaw": "tahterevalli",
    "shopping cart": "alışveriş arabası",
    "skatepark": "kaykay parkı",
    "sliding door": "sürgülü kapı",
    "soccer field": "futbol sahası",
    "sofa": "kanepe",
    "space heater": "ısıtıcı",
    "speed bump": "kasis",
    "spiral staircase": "spiral merdiven",
    "sports arena": "spor arenası",
    "sprinkler": "sulama sistemi",
    "storage room": "depo odası",
    "stroller": "bebek arabası",
    "swings": "salıncak",
    "ticket booth": "bilet gişesi",
    "traffic cone": "trafik konisi",
    "trampoline": "trambolin",
    "treehouse": "ağaç ev",
    "trolley": "el arabası",
    "umbrella stand": "şemsiye standı",
    "vacuum cleaner": "elektrik süpürgesi",
    "vegetable patch": "sebze bahçesi",
    "vending machine": "otomat",
    "waiting room": "bekleme odası",
    "water tank": "su deposu",
    "wheelbarrow": "el arabası",
    "wind chime": "rüzgar çanı",
    "zebra crossing": "yaya geçidi"
    },
    "B1": {
    "abstract": "soyut",
    "adventure": "macera",
    "advice": "tavsiye",
    "analysis": "analiz",
    "apology": "özür",
    "architecture": "mimari",
    "argument": "tartışma",
    "arrival": "varış",
    "audience": "seyirci",
    "background": "arka plan",
    "balance": "denge",
    "behavior": "davranış",
    "biography": "biyografi",
    "border": "sınır",
    "career": "kariyer",
    "celebration": "kutlama",
    "challenge": "zorluk",
    "championship": "şampiyona",
    "character": "karakter",
    "chemistry": "kimya",
    "choice": "seçim",
    "climate": "iklim",
    "collection": "koleksiyon",
    "communication": "iletişim",
    "competition": "yarışma",
    "complaint": "şikayet",
    "conclusion": "sonuç",
    "confidence": "özgüven",
    "conflict": "çatışma",
    "connection": "bağlantı",
    "construction": "inşaat",
    "consumer": "tüketici",
    "contrast": "karşıtlık",
    "courage": "cesaret",
    "criminal": "suçlu",
    "criticism": "eleştiri",
    "culture": "kültür",
    "curiosity": "merak",
    "customer": "müşteri",
    "decision": "karar",
    "delivery": "teslimat",
    "departure": "kalkış",
    "description": "tanım",
    "destination": "varış yeri",
    "development": "gelişim",
    "disaster": "felaket",
    "discussion": "tartışma",
    "document": "belge",
    "education": "eğitim",
    "efficiency": "verimlilik",
    "emotion": "duygu",
    "energy": "enerji",
    "environment": "çevre",
    "equipment": "ekipman",
    "establishment": "kuruluş",
    "experience": "deneyim",
    "explanation": "açıklama",
    "expression": "ifade",
    "facility": "tesis",
    "fiction": "kurgu",
    "freedom": "özgürlük",
    "friendship": "arkadaşlık",
    "furniture": "mobilya",
    "generation": "nesil",
    "government": "hükümet",
    "growth": "büyüme",
    "guidance": "rehberlik",
    "happiness": "mutluluk",
    "health": "sağlık",
    "history": "tarih",
    "homework": "ödev",
    "identity": "kimlik",
    "imagination": "hayal gücü",
    "importance": "önem",
    "improvement": "geliştirme",
    "independence": "bağımsızlık",
    "industry": "sanayi",
    "information": "bilgi",
    "innovation": "yenilik",
    "instruction": "talimat",
    "investment": "yatırım",
    "involvement": "katılım",
    "journal": "günlük",
    "journey": "yolculuk",
    "justice": "adalet",
    "knowledge": "bilgi",
    "language": "dil",
    "leadership": "liderlik",
    "learning": "öğrenme",
    "literature": "edebiyat",
    "location": "konum",
    "management": "yönetim",
    "marketing": "pazarlama",
    "medicine": "tıp",
    "membership": "üyelik",
    "memory": "hafıza",
    "message": "mesaj",
    "mistake": "hata",
    "movement": "hareket",
    "natural": "doğal",
    "negotiation": "müzakere",
    "opinion": "görüş",
    "opportunity": "fırsat",
    "organization": "organizasyon",
    "participation": "katılım",
    "partnership": "ortaklık",
    "performance": "performans",
    "permission": "izin",
    "personality": "kişilik",
    "photograph": "fotoğraf",
    "pollution": "kirlilik",
    "population": "nüfus",
    "possibility": "olasılık",
    "preference": "tercih",
    "presentation": "sunum",
    "prevention": "önleme",
    "procedure": "prosedür",
    "production": "üretim",
    "progress": "ilerleme",
    "protection": "koruma",
    "publication": "yayın",
    "punishment": "ceza",
    "questionnaire": "anket",
    "reception": "resepsiyon",
    "recognition": "tanıma",
    "recommendation": "tavsiye",
    "reflection": "yansıma",
    "relationship": "ilişki",
    "reliability": "güvenilirlik",
    "requirement": "gereklilik",
    "research": "araştırma",
    "resolution": "çözüm",
    "responsibility": "sorumluluk",
    "satisfaction": "memnuniyet",
    "scholarship": "burs",
    "security": "güvenlik",
    "signature": "imza",
    "situation": "durum",
    "solution": "çözüm",
    "strategy": "strateji",
    "strength": "güç",
    "structure": "yapı",
    "success": "başarı",
    "suggestion": "öneri",
    "support": "destek",
    "surprise": "sürpriz",
    "technology": "teknoloji",
    "temperature": "sıcaklık",
    "tradition": "gelenek",
    "transportation": "ulaşım",
    "understanding": "anlayış",
    "university": "üniversite",
    "vacation": "tatil",
    "variation": "varyasyon",
    "victory": "zafer",
    "violence": "şiddet",
    "volunteer": "gönüllü",
    "weakness": "zayıflık",
    "weather": "hava durumu",
    "welfare": "refah",
    "witness": "tanık",
    "youth": "gençlik"
    },
    "B2": {
    "abandon": "terk etmek",
    "accomplishment": "başarı",
    "accountability": "sorumluluk",
    "adaptation": "uyarlama",
    "advancement": "ilerleme",
    "affection": "sevgi",
    "allocation": "tahsis",
    "ambiguity": "belirsizlik",
    "amendment": "düzeltme",
    "anticipation": "beklenti",
    "appreciation": "takdir",
    "architecture": "mimarlık",
    "assessment": "değerlendirme",
    "association": "dernek",
    "atmosphere": "atmosfer",
    "attitude": "tavır",
    "authenticity": "özgünlük",
    "authority": "otorite",
    "balance": "denge",
    "barrier": "engel",
    "behavioral": "davranışsal",
    "biodiversity": "biyolojik çeşitlilik",
    "boundary": "sınır",
    "capacity": "kapasite",
    "certainty": "kesinlik",
    "challenge": "meydan okuma",
    "collaboration": "işbirliği",
    "commitment": "bağlılık",
    "compassion": "şefkat",
    "complexity": "karmaşıklık",
    "compliance": "uyumluluk",
    "compromise": "uzlaşma",
    "concentration": "konsantrasyon",
    "conclusion": "sonuç",
    "consistency": "tutarlılık",
    "constraint": "kısıtlama",
    "consultation": "danışma",
    "contamination": "kirlilik",
    "contribution": "katkı",
    "controversy": "tartışma",
    "cooperation": "iş birliği",
    "corruption": "yolsuzluk",
    "credibility": "güvenilirlik",
    "criterion": "ölçüt",
    "curiosity": "merak",
    "dedication": "adama",
    "definition": "tanım",
    "deliberation": "müzakere",
    "democracy": "demokrasi",
    "dependence": "bağımlılık",
    "derivation": "türetim",
    "determination": "kararlılık",
    "differentiation": "ayrım",
    "discrimination": "ayrımcılık",
    "diversity": "çeşitlilik",
    "dominance": "hakimiyet",
    "effectiveness": "etkililik",
    "efficiency": "verimlilik",
    "elaboration": "detaylandırma",
    "emphasis": "vurgulama",
    "enlightenment": "aydınlanma",
    "entrepreneurship": "girişimcilik",
    "equity": "eşitlik",
    "essence": "öz",
    "establishment": "kuruluş",
    "evaluation": "değerlendirme",
    "evolution": "evrim",
    "exception": "istisna",
    "exclusion": "dışlama",
    "expectation": "beklenti",
    "expertise": "uzmanlık",
    "exploitation": "sömürü",
    "extension": "genişletme",
    "facilitation": "kolaylaştırma",
    "feasibility": "uygulanabilirlik",
    "flexibility": "esneklik",
    "fragmentation": "parçalanma",
    "framework": "çerçeve",
    "fulfillment": "yerine getirme",
    "fundamentals": "temeller",
    "governance": "yönetim",
    "guidance": "rehberlik",
    "heritage": "miras",
    "hierarchy": "hiyerarşi",
    "hospitality": "misafirperverlik",
    "implementation": "uygulama",
    "incentive": "teşvik",
    "inclusion": "dahil etme",
    "independence": "bağımsızlık",
    "indicator": "gösterge",
    "infrastructure": "altyapı",
    "innovation": "yenilik",
    "insight": "içgörü",
    "integrity": "bütünlük",
    "interaction": "etkileşim",
    "interpretation": "yorumlama",
    "intervention": "müdahale",
    "investment": "yatırım",
    "justification": "gerekçe",
    "legislation": "yasama",
    "limitation": "sınırlama",
    "manifestation": "tezahür",
    "mediation": "arabuluculuk",
    "methodology": "yöntembilim",
    "motivation": "motivasyon",
    "negotiation": "müzakere",
    "neutrality": "tarafsızlık",
    "observation": "gözlem",
    "optimization": "optimizasyon",
    "orientation": "yönlendirme",
    "parameter": "parametre",
    "participation": "katılım",
    "partnership": "ortaklık",
    "phenomenon": "olgu",
    "philosophy": "felsefe",
    "portfolio": "portföy",
    "practitioner": "pratisyen",
    "precedent": "örnek",
    "prediction": "tahmin",
    "preference": "tercih",
    "preliminary": "ön hazırlık",
    "preservation": "koruma",
    "priority": "öncelik",
    "probability": "olasılık",
    "procedure": "prosedür",
    "proficiency": "yeterlilik",
    "projection": "projeksiyon",
    "proportion": "oran",
    "prosperity": "refah",
    "protocol": "protokol",
    "qualification": "nitelik",
    "recognition": "tanınma",
    "reconciliation": "uzlaşma",
    "reflection": "yansıma",
    "regulation": "düzenleme",
    "reinforcement": "pekiştirme",
    "reliability": "güvenilirlik",
    "resilience": "dayanıklılık",
    "restriction": "kısıtlama",
    "retrospective": "geçmişe dönük",
    "sensitivity": "hassasiyet",
    "significance": "önem",
    "simulation": "benzetim",
    "stability": "istikrar",
    "sustainability": "sürdürülebilirlik",
    "synthesis": "sentez",
    "transparency": "şeffaflık",
    "utilization": "kullanım",
    "validation": "doğrulama",
    "variability": "değişkenlik",
    "viability": "uygulanabilirlik"
    },
    "C1": {
   "acquisition": "edinim",
    "advocacy": "savunuculuk",
    "alignment": "hizalama",
    "anecdote": "anekdot",
    "antithesis": "karşıtlık",
    "articulation": "ifade",
    "aspiration": "hedef",
    "authenticity": "özgünlük",
    "autonomy": "özerklik",
    "bargaining": "pazarlık",
    "benchmark": "ölçüt",
    "bilateral": "ikili",
    "bureaucracy": "bürokrasi",
    "capability": "yetkinlik",
    "capitalism": "kapitalizm",
    "catastrophe": "felaket",
    "chronology": "kronoloji",
    "citizenship": "vatandaşlık",
    "coherence": "tutarlılık",
    "collaboration": "iş birliği",
    "competence": "yeterlik",
    "compliance": "uyumluluk",
    "conformity": "uyum",
    "consensus": "fikir birliği",
    "constituency": "seçim bölgesi",
    "contention": "tartışma",
    "continuity": "süreklilik",
    "contradiction": "çelişki",
    "credibility": "güvenilirlik",
    "culmination": "doruk noktası",
    "declaration": "beyan",
    "deduction": "çıkarım",
    "deficiency": "eksiklik",
    "deviation": "sapma",
    "dichotomy": "ikilik",
    "dilemma": "ikilem",
    "disparity": "farklılık",
    "empowerment": "güçlendirme",
    "endeavour": "çaba",
    "enrichment": "zenginleştirme",
    "equilibrium": "denge",
    "ethnicity": "etnisite",
    "exemplification": "örnekleme",
    "feasibility": "uygulanabilirlik",
    "fluidity": "akışkanlık",
    "generalization": "genelleme",
    "globalization": "küreselleşme",
    "heterogeneity": "çeşitlilik",
    "hierarchy": "hiyerarşi",
    "ideology": "ideoloji",
    "impartiality": "tarafsızlık",
    "implementation": "uygulama",
    "incentive": "teşvik",
    "inclination": "eğilim",
    "indispensability": "vazgeçilmezlik",
    "inevitability": "kaçınılmazlık",
    "ingenuity": "yaratıcılık",
    "inherently": "doğal olarak",
    "innovation": "yenilik",
    "integrity": "dürüstlük",
    "interaction": "etkileşim",
    "intervention": "müdahale",
    "legitimacy": "meşruiyet",
    "manifestation": "görünüm",
    "marginalization": "dışlanma",
    "methodology": "yöntem bilimi",
    "modernization": "modernleşme",
    "nationalism": "milliyetçilik",
    "negligence": "ihmal",
    "optimization": "optimizasyon",
    "paradigm": "paradigma",
    "polarization": "kutuplaşma",
    "prevalence": "yaygınlık",
    "privilege": "ayrıcalık",
    "proliferation": "çoğalma",
    "propensity": "yatkınlık",
    "proposition": "önerme",
    "qualification": "nitelik",
    "ramification": "dallanma",
    "rationality": "rasyonellik",
    "reconciliation": "uzlaşma",
    "redistribution": "yeniden dağıtım",
    "reflection": "yansıma",
    "refinement": "rafine etme",
    "reinforcement": "pekiştirme",
    "reliability": "güvenilirlik",
    "resilience": "direnç",
    "restoration": "yenileme",
    "segmentation": "bölümlendirme",
    "sovereignty": "egemenlik",
    "specification": "spesifikasyon",
    "stabilization": "istikrar",
    "standardization": "standartlaştırma",
    "stratification": "tabakalaşma",
    "subordination": "bağlılık",
    "sustainability": "sürdürülebilirlik",
    "synergy": "sinerji",
    "transformation": "dönüşüm",
    "transparency": "şeffaflık",
    "unification": "birleşme",
    "utilization": "kullanım",
    "validity": "geçerlilik",
    "variability": "değişkenlik",
    "viability": "uygulanabilirlik",
    "vulnerability": "savunmasızlık",
    "abbreviation": "kısaltma",
    "adversity": "sıkıntı",
    "affiliation": "bağlılık",
    "allegation": "iddia",
    "allocation": "tahsis",
    "analogy": "benzetme",
    "anticipation": "beklenti",
    "appraisal": "değer biçme",
    "assimilation": "benimseme",
    "asymmetry": "asimetriklik",
    "autonomy": "özerklik",
    "benevolence": "iyilikseverlik",
    "bureaucratic": "bürokratik",
    "coexistence": "birlikte var olma",
    "collaboration": "iş birliği",
    "compatibility": "uyumluluk",
    "concealment": "gizleme",
    "conscientiousness": "vicdanlılık",
    "consolidation": "güçlendirme",
    "contingency": "olasılık",
    "culmination": "zirve",
    "decentralization": "merkeziyetçilik",
    "deductibility": "kesilebilirlik",
    "defensiveness": "savunma pozisyonu",
    "deliberation": "üzerinde düşünme",
    "deprivation": "yoksunluk",
    "desirability": "arzulanabilirlik",
    "detrimental": "zararlı",
    "differentiation": "farklılaştırma",
    "dissemination": "yayma",
    "diversification": "çeşitlendirme",
    "dominance": "hakimiyet",
    "effectiveness": "etkililik",
    "elucidation": "açıklama",
    "emancipation": "özgürleşme",
    "epistemology": "bilgi felsefesi",
    "feasibility": "uygulanabilirlik",
    "fragmentation": "parçalanma",
    "homogeneity": "homojenlik",
    "idiosyncrasy": "kişisel özellik",
    "incomprehensibility": "anlaşılmazlık",
    "indivisibility": "bölünmezlik",
    "legitimization": "meşrulaştırma",
    "materialization": "gerçekleşme",
    "necessitation": "gereklilik",
    "objectification": "nesneleştirme",
    "overgeneralization": "aşırı genelleme",
    "professionalism": "profesyonellik",
    "radicalization": "radikalleşme",
    "regionalization": "bölgeselleştirme",
    "specialization": "uzmanlık",
    "stabilization": "dengelenme",
    "transgression": "aşım",
    "unattainability": "ulaşılamazlık"
    },
    "C2": {
    "achievement": "başarı",
    "ambition": "hırs",
    "anxiety": "kaygı",
    "articulate": "açıkça ifade etmek",
    "benevolent": "iyiliksever",
    "catastrophe": "felaket",
    "compassion": "şefkat",
    "dedication": "adanmışlık",
    "determination": "kararlılık",
    "discrepancy": "tutarsızlık",
    "elaborate": "detaylandırmak",
    "exquisite": "zarif",
    "gratitude": "şükran",
    "hypothetical": "varsayımsal",
    "inevitable": "kaçınılmaz",
    "meticulous": "titiz",
    "perseverance": "azim",
    "resilience": "dayanıklılık",
    "sophisticated": "sofistike",
    "tranquility": "huzur",
    "ubiquitous": "her yerde olan",
    "versatile": "çok yönlü",
    "vivid": "canlı",
    "wholesome": "sağlıklı",
    "zealous": "gayretli",
    "abundance": "bolluk",
    "alleviate": "hafifletmek",
    "anticipation": "beklenti",
    "authentic": "gerçek",
    "bewildered": "şaşkın",
    "commendable": "övgüye değer",
    "conspicuous": "göze çarpan",
    "contradiction": "çelişki",
    "deviation": "sapma",
    "diligence": "çalışkanlık",
    "distinctive": "belirgin",
    "efficiency": "verimlilik",
    "enlighten": "aydınlatmak",
    "enthralling": "büyüleyici",
    "equilibrium": "denge",
    "eradicate": "kökünü kazımak",
    "exceptional": "olağanüstü",
    "fluctuation": "dalgalanma",
    "foreseeable": "tahmin edilebilir",
    "gratifying": "memnun edici",
    "harmonious": "uyumlu",
    "imperative": "zorunlu",
    "inaugurate": "açılış yapmak",
    "indispensable": "vazgeçilmez",
    "ineffable": "tarif edilemez",
    "innovation": "yenilik",
    "intangible": "soyut",
    "intriguing": "ilgi çekici",
    "luminescent": "ışıltılı",
    "magnanimous": "bağışlayıcı",
    "manifestation": "görünüm",
    "metamorphosis": "başkalaşım",
    "nostalgia": "nostalji",
    "oblivion": "unutulma",
    "omniscient": "her şeyi bilen",
    "paradigm": "model",
    "phenomenon": "olgu",
    "plethora": "aşırılık",
    "profound": "derin",
    "proliferate": "hızla çoğalmak",
    "quintessential": "en özlü",
    "reconciliation": "uzlaşma",
    "refinement": "zarafet",
    "retrospective": "geçmişe dönük",
    "serendipity": "şans eseri bulma",
    "steadfast": "sabit",
    "sublime": "yüce",
    "succinct": "özlü",
    "superficial": "yüzeysel",
    "synergy": "iş birliği",
    "tenacious": "inatçı",
    "transcend": "aşmak",
    "ubiquity": "her yerde olma",
    "unprecedented": "eşi görülmemiş",
    "vulnerability": "savunmasızlık",
    "wistful": "hüzünlü",
    "zealotry": "fanatizm",
    "abdicate": "çekilmek",
    "ambiguous": "belirsiz",
    "anachronism": "zaman yanılgısı",
    "anecdotal": "hikaye tarzında",
    "antithesis": "karşıtlık",
    "aspiration": "arzu",
    "authenticity": "özgünlük",
    "belligerent": "savaşçı",
    "benevolence": "iyilik",
    "camouflage": "kamuflaj",
    "capricious": "kararsız",
    "clairvoyant": "sezgili",
    "cohesive": "bağlayıcı",
    "collaboration": "iş birliği",
    "complacency": "rehavet",
    "comprehensive": "kapsamlı",
    "conciliatory": "uzlaşmacı",
    "consequential": "önemli",
    "conundrum": "bilmece",
    "credibility": "güvenilirlik",
    "culmination": "doruk",
    "cumbersome": "hantal",
    "curiosity": "merak",
    "deferential": "saygılı",
    "dichotomy": "ikilem",
    "discernible": "ayırt edilebilir",
    "effervescent": "coşkulu",
    "ephemeral": "kısa ömürlü",
    "epiphany": "aydınlanma",
    "equanimity": "soğukkanlılık",
    "euphemism": "örtmece",
    "facetious": "şakacı",
    "fallacy": "yanılgı",
    "fortitude": "cesaret",
    "hierarchy": "hiyerarşi",
    "idiosyncrasy": "kendine özgü özellik",
    "ineptitude": "beceriksizlik",
    "inquisitive": "meraklı",
    "juxtaposition": "yan yana koyma",
    "lucid": "açık",
    "meander": "dolambaçlı yol",
    "nonchalant": "kayıtsız",
    "nuance": "ince ayrım",
    "obstinate": "inatçı",
    "paradoxical": "çelişkili",
    "perplexing": "kafa karıştırıcı",
    "pragmatic": "pratik",
    "precocious": "erken gelişmiş",
    "procrastinate": "ertelemek",
    "quintessential": "temsil eden",
    "redundant": "gereksiz",
    "rejuvenate": "gençleştirmek",
    "repercussion": "yansıma",
    "resonance": "tını",
    "scrutiny": "inceleme",
    "solitude": "yalnızlık",
    "spontaneous": "kendiliğinden",
    "substantiate": "doğrulamak",
    "synthesis": "sentez",
    "taciturn": "suskun",
    "transience": "geçicilik",
    "ubiquitous": "yaygın",
    "veracity": "doğruluk",
    "whimsical": "oynak",
    "xenophobia": "yabancı düşmanlığı",
    "yonder": "öteki taraf",
    "zenith": "zirve"
    }
}

def select_language(screen):
    while True:
        screen.clear()
        screen.addstr(1, 2, "Dil yönünü seçin:")
        screen.addstr(3, 4, "1. İngilizce → Türkçe")
        screen.addstr(4, 4, "2. Türkçe → İngilizce")
        screen.addstr(6, 2, "Seçiminiz: ")

        curses.echo()
        choice = screen.getstr(6, 14).decode("utf-8").strip()
        curses.noecho()

        if choice == "1":
            return "en_to_tr"
        elif choice == "2":
            return "tr_to_en"
        else:
            screen.addstr(8, 2, "Geçersiz seçim. Tekrar deneyin.")
            screen.refresh()
            time.sleep(2)

def select_level(screen):
    levels = {"1": "A1", "2": "A2", "3": "B1", "4": "B2", "5": "C1", "6": "C2"}
    while True:
        screen.clear()
        screen.addstr(1, 2, "Seviyenizi seçin:")
        screen.addstr(3, 4, "1. A1")
        screen.addstr(4, 4, "2. A2")
        screen.addstr(5, 4, "3. B1")
        screen.addstr(6, 4, "4. B2")
        screen.addstr(7, 4, "5. C1")
        screen.addstr(8, 4, "6. C2")
        screen.addstr(10, 2, "Seçiminiz: ")

        curses.echo()
        choice = screen.getstr(10, 14).decode("utf-8").strip()
        curses.noecho()

        if choice in levels:
            return levels[choice]
        else:
            screen.addstr(12, 2, "Geçersiz seçim. Tekrar deneyin.")
            screen.refresh()
            time.sleep(2)

def select_question_count(screen):
    while True:
        screen.clear()
        screen.addstr(1, 2, "Kaç soru çözmek istersiniz? (1-20):")
        screen.addstr(3, 2, "Seçiminiz: ")

        curses.echo()
        count = screen.getstr(3, 14).decode("utf-8").strip()
        curses.noecho()

        if count.isdigit() and 1 <= int(count) <= 20:
            return int(count)
        else:
            screen.addstr(5, 2, "Geçersiz giriş. Tekrar deneyin.")
            screen.refresh()
            time.sleep(2)

def ask_questions(screen, language, level, question_count):
    questions = list(word_dict[level].items())
    random.shuffle(questions)

    correct_answers = 0

    for i in range(question_count):
        screen.clear()
        screen.border(0)

        question, answer = questions[i]

        if language == "en_to_tr":
            screen.addstr(2, 2, f"Soru {i + 1}/{question_count}:")
            screen.addstr(4, 2, f"'{question}' kelimesinin Türkçesi nedir?")
            correct_option = answer
        else:
            screen.addstr(2, 2, f"Soru {i + 1}/{question_count}:")
            screen.addstr(4, 2, f"'{answer}' kelimesinin İngilizcesi nedir?")
            correct_option = question

        options = [correct_option]
        while len(options) < 4:
            if language == "en_to_tr":
                _, wrong_option = random.choice(questions)
            else:
                wrong_option, _ = random.choice(questions)

            if wrong_option not in options:
                options.append(wrong_option)

        random.shuffle(options)

        for idx, option in enumerate(options):
            screen.addstr(6 + idx, 4, f"{idx + 1}. {option}")

        screen.addstr(11, 2, "Seçiminiz: ")

        curses.echo()
        user_choice = screen.getstr(11, 14).decode("utf-8").strip()
        curses.noecho()

        if user_choice.isdigit() and 1 <= int(user_choice) <= 4:
            selected_answer = options[int(user_choice) - 1]
            if selected_answer == correct_option:
                correct_answers += 1
                screen.addstr(13, 2, "Doğru! ✅")
            else:
                screen.addstr(13, 2, f"Yanlış. ❌ Doğru cevap: {correct_option}")
        else:
            screen.addstr(13, 2, "Geçersiz seçim. Bu soru atlandı.")

        screen.refresh()
        time.sleep(2)

    return correct_answers

def show_results(screen, correct_answers, question_count):
    screen.clear()
    screen.border(0)
    screen.addstr(2, 2, "Quiz Tamamlandı!")
    screen.addstr(4, 2, f"Toplam Soru: {question_count}")
    screen.addstr(5, 2, f"Doğru Cevaplar: {correct_answers}")
    accuracy = (correct_answers / question_count) * 100
    screen.addstr(6, 2, f"Başarı Oranı: %{accuracy:.2f}")
    screen.addstr(8, 2, "Tekrar oynamak için bir tuşa basın...")
    screen.refresh()
    screen.getch()

def main(screen):
    while True:
        language = select_language(screen)
        level = select_level(screen)
        question_count = select_question_count(screen)
        correct_answers = ask_questions(screen, language, level, question_count)
        show_results(screen, correct_answers, question_count)

if __name__ == "__main__":
    curses.wrapper(main)
